site_name: DecentralizedGeo-hub # Your project name
site_description: A collection of resources for the Decentralized Geospatial ecosystem.

theme:
  # logo: https://avatars.githubusercontent.com/u/199006257?s=200&v=4
  name: material
  palette:
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/lightbulb-auto
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

repo_name: DecentralizedGeo
repo_url: https://github.com/DecentralizedGeo
plugins:
  # Material for MkDocs
  search:

nav: # Navigation links
  - DecentralizedGeo: index.md # Home page
  - ipfs-stac:
      - Introduction: https://decentralizedgeo.github.io/ipfs-stac/
  - Web3 Geo-Dashboard:
      - Introduction: ./ecosystem/web3-geospatial-dashboard/index.md
      - Getting Started: ./ecosystem/web3-geospatial-dashboard/getting-started.md
      - How-to-Guides:
          - Features: ./ecosystem/web3-geospatial-dashboard/features.md
          - Veda Integration: ./ecosystem/web3-geospatial-dashboard/veda.md
      - Reference:
          - Tech Stack: ./ecosystem/web3-geospatial-dashboard/tech-stack.md
          - Prerequisites: ./ecosystem/web3-geospatial-dashboard/prerequisites.md

  - astral-api:
      - Introduction: ./ecosystem/astral-api/index.md
      - Getting Started: ./ecosystem/astral-api/getting-started.md
      - API Reference: ./ecosystem/astral-api/api-reference.md
      - Data Model: ./ecosystem/astral-api/data-model.md
      - Spatial Queries: ./ecosystem/astral-api/spatial-queries.md
      - Authentication: ./ecosystem/astral-api/authentication.md
      - Troubleshooting: ./ecosystem/astral-api/troubleshooting.md
      - OGC API: ./ecosystem/astral-api/ogc-api.md
      - GraphQL API: ./ecosystem/astral-api/graphql-api.md
      - Documentation Review: ./ecosystem/astral-api/documentation-review.md # If you want to include internal docs
  - Astral Logbook:
      - Introduction: ./ecosystem/astral-logbook/index.md
      - Getting Started: ./ecosystem/astral-logbook/getting-started.md
      - Technology Stack: ./ecosystem/astral-logbook/technology-stack.md
      - Prerequisites: ./ecosystem/astral-logbook/prerequisites.md
      - Deployment Guide: ./ecosystem/astral-logbook/deployment-guide.md
      - Troubleshooting: ./ecosystem/astral-logbook/troubleshooting.md
  - Contribute:
      - Contributing Guidelines: ./contribute/contributing-guidelines.md
      - Style Guide: ./style-guidelines.md
      - Documention Guide: ./documentation-guidelines.md
      - Support: ./contribute/support.md
      - Code of Conduct: ./contribute/CODE_OF_CONDUCT.md

markdown_extensions:
  - md_in_html:
  - tables:
  - toc:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
